# Generated by Django 5.1.3 on 2025-01-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2025-01-14'),
            preserve_default=False,
        ),
    ]
