# Generated by Django 5.1.3 on 2024-12-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewuserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('place', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, max_length=30, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.logintable')),
            ],
        ),
    ]
