# Generated by Django 5.1.4 on 2024-12-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_viewusertable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewuserTable',
        ),
    ]
