# Generated by Django 5.1.3 on 2025-01-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_usertable_bmi_usertable_calorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttable',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posttable',
            name='workoutday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
