# Generated by Django 5.1.3 on 2025-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_usertable_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
