# Generated by Django 5.1.3 on 2025-01-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_posttable_type_posttable_workoutday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttable',
            old_name='video',
            new_name='videos',
        ),
    ]
