# Generated by Django 5.1.3 on 2024-12-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_delete_viewusertable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdtable',
            old_name='DIETITIAN',
            new_name='DIETITION',
        ),
    ]
