# Generated by Django 5.1.3 on 2024-12-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_rename_dietitian_bookingdtable_dietition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdtable',
            name='details',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
