# Generated by Django 5.1.3 on 2024-12-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_bookingdtable_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingttable',
            name='details',
        ),
    ]
