# Generated by Django 5.1.3 on 2025-01-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_chat_delete_chattable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
