# Generated by Django 5.1.3 on 2024-12-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_remove_bookingttable_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdtable',
            name='details',
        ),
    ]
