# Generated by Django 5.1.3 on 2024-12-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_remove_bookingdtable_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdtable',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='bookingdtable',
            old_name='name',
            new_name='No',
        ),
        migrations.RenameField(
            model_name='bookingdtable',
            old_name='status',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='bookingdtable',
            name='USER',
        ),
        migrations.AddField(
            model_name='bookingdtable',
            name='Username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
