# Generated by Django 5.1.3 on 2024-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_rename_date_bookingdtable_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
